### ISSUE TITLE
Remove "provider type alignment" `@ts-expect-error` directives

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/smart-transactions-controller#240]
The `// @ts-expect-error TODO: Provider type alignment` directives introduced in https://github.com/MetaMask/smart-transactions-controller/pull/237, and the `any` typing for provider can be fixed once the next version of `@metamask/controller-utils` (currently 5.0.2) is released. 

- See https://github.com/MetaMask/core/issues/1823#issuecomment-1823347834

**Comment by Gudahtt** [comment]
These `@ts-expect-error` entries do not appear to exist. I can't see them in the linked PR, maybe they were removed prior to merge.
