### ISSUE TITLE
Update to BaseControllerV2

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/smart-transactions-controller#385]
Update this controller to use the new BaseController class (here: https://github.com/MetaMask/core/blob/448f8f02378be606beecdc436c5f5cc59dd906c9/packages/base-controller/src/BaseControllerV2.ts).

The BaseControllerV1 class currently in-use is deprecated and no longer maintained. It will soon be removed. This is one of the last two instances, and is currently blocking some improvements to extension and mobile state management that require the use of BaseControllerV1.

## Acceptance Criteria

- A constant called `controllerName` exists which holds the name of the controller.
- A constant called `controllerMetadata` exists which holds the metadata for the state.
- The default state object is extracted out of the constructor to a function called `getDefaultSmartTransactionsControllerState`.
- `SmartTransactionsController` inherits from `StaticIntervalPollingController` instead of `StaticIntervalPollingControllerV1`.
  - The `SmartTransactionsController` constructor signature is updated to take a single options bag instead of three arguments, with options in `config` merged into options not in `state` or `config`.
  - The constructor no longer takes `onNetworkStateChange`, but subscribes to `NetworkController:stateChange`.
    - Note that this requires upgrading `@metamask/network-controller` to v20 first.
  - The constructor no longer takes `getNetworkClientById`, but calls this through the messenger instead.
  - The controller no longer subscribes to itself by calling `subscribe` on itself, but on the messenger instead.
- An `EventEmitter` is no longer to emit events, but the messenger is used instead.
- Supporting types exist and/or are updated.
- - The `SmartTransactionsControllerConfig` type no longer exists, and is renamed to `SmartTransactionsControllerOptions`.
  - The `SmartTransactionsControllerGetStateAction` and `SmartTransactionsControllerStateChangeEvent` types exist.
  - The `SmartTransactionsControllerSmartTransactionEvent` type exists.
  - The `SmartTransactionsControllerActions` type exists (it is simply `never`).
  - The `SmartTransactionsControllerEvents` type exists, and includes `SmartTransactionsControllerSmartTransactionEvent`.
  - The `AllowedActions` type exists, and includes `NetworkControllerGetNetworkClientByIdAction`.
  - and `AllowedEvents` type exists, and includes `NetworkControllerStateChangeEvent`.
  - The `SmartTransactionsControllerMessenger` type exists and expects `NetworkController:getNetworkClientById` and `NetworkController:stateChange` to be allowed.
  - The `SmartTransactionsControllerState` type no longer intersects with `BaseState` from BaseController v1.
- The tests are updated to follow suit.
  - The tests make use of `getDefaultSmartTransactionsControllerState` instead of recreating default state.
  - Tests that access `smartTransactionsController.config.*` (which is no longer accessible) are either rewritten or removed.
  - A messenger is created in `beforeEach`.

**Comment by desi** [comment]
@cryptodev-2s We moved this to the top of ready for dev so that a teammate could pick up and sort out the CI issues and help move this forward.

**Comment by cryptodev-2s** [comment]
@desi if we run the step that fails with only it succeeds. It should only be an issue with steps not running independently.

I can look up this in the evening

**Comment by cryptodev-2s** [comment]
@desi I moved back this to needs dev review. Unit Tests has been fixed.
