### ISSUE TITLE
Bug: Remove test-helpers.ts from the list of release files

### ISSUE THREAD

**Issue by kanthesha** [MetaMask/smart-transactions-controller#400]
We can see the test-helpers getting into the list of release files, which is not supposed to. 
<img width="843" alt="Screenshot 2024-08-02 at 13 31 54" src="https://github.com/user-attachments/assets/ad4e5f57-cdf4-4a4f-be2e-cc9dec7e7f74">

**Comment by Gudahtt** [comment]
Fixed by #459
